ALTER TABLE "CierreCaja" ADD COLUMN "totalCobrosCredito" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "CierreCaja" ADD COLUMN "cobroCreditoEfectivo" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "CierreCaja" ADD COLUMN "cobroCreditoTransferencia" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "CierreCaja" ADD COLUMN "cobroCreditoQr" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "CierreCaja" ADD COLUMN "cobroCreditoTarjeta" DOUBLE PRECISION NOT NULL DEFAULT 0;
